Add feed
aleskerovv/java-filmorate pull request #10
Opened 2022-11-05 00:55 UTC by TomatoSoup0451

Добавил ленту событий для лайков и дружбы. По рецензиям потом добавлю, как появятся. Постмановские тесты проходит кроме тех, что касаются рецензий

2022-11-05 07:33 UTC, aleskerovv approved these changes
Всё хорошо, комментарий добавил

2022-11-05 07:33 UTC, aleskerovv commented on src/main/java/ru/yandex/practicum/filmorate/model/Event.java
> +    @Setter
@Setter аннотацию можно убрать, аннотация @Data создает сеттеры для всех полей

2022-11-05 07:47 UTC, TomatoSoup0451 commented on src/main/java/ru/yandex/practicum/filmorate/model/Event.java
> +    @Setter
Ага, тут меня что-то переклинило

2022-11-05 11:02 UTC, AdalizEentropy requested changes

2022-11-05 11:02 UTC, AdalizEentropy commented on src/main/java/ru/yandex/practicum/filmorate/model/Event.java
> +    private final Timestamp timestamp;
Не уверена, что в джаве такой формат времени используется, это чисто БДшный тип. Лучше наверное сделать LocalDateTime

2022-11-05 11:02 UTC, AdalizEentropy commented on src/main/java/ru/yandex/practicum/filmorate/model/Event.java
> +    public enum EventType{
(opt) А не хочешь их вынести в отдельные классы, в отдельный пекедж enums ? Его потом удобнее использовать в других классах, без сложных конструкций типа "Event.EventType.FRIEND"

2022-11-05 11:02 UTC, AdalizEentropy commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:h2:mem:testdb
Надо будет не забыть вернуть базу в файле

2022-11-05 11:02 UTC, AdalizEentropy commented on src/main/java/ru/yandex/practicum/filmorate/storage/feed/EventDbStorage.java
> +    private void isUserExists(int id) {
Мне кажется, что тут дублирование кода. Можно проверять наличие юзера через уже имеющийся метод public User findById(Integer id) в UserDbStorage. Чтобы не тащить сюда зависимость UserDbStorage, можно эту проверку сделать в сервисе.

2022-11-05 11:02 UTC, AdalizEentropy commented on src/main/java/ru/yandex/practicum/filmorate/storage/feed/EventDbStorage.java
> +            throw new NotFoundException("id", String.format("user with id %d not found", id));
Тут скорее не "user with id %d not found", id", а "events with user id $id not found", чтобы не вводить в заблуждение фронт =)
Но даже дело в другом. Ты уверен, что тут такой эксепшен вылезет? Похоже, если в этой таблице ничего не найдется, то query вернет пустой лист.

2022-11-05 11:02 UTC, AdalizEentropy commented on src/main/java/ru/yandex/practicum/filmorate/storage/feed/EventDbStorage.java
> +        String query = "SELECT event_id, user_id, event_id, user_id, timestamp, event_type," +
два раза event_id, user_id

2022-11-05 12:40 UTC, TomatoSoup0451 commented on src/main/java/ru/yandex/practicum/filmorate/model/Event.java
> +    private final Timestamp timestamp;
Принято, заменил

2022-11-05 12:57 UTC, TomatoSoup0451 commented on src/main/java/ru/yandex/practicum/filmorate/model/Event.java
> +    public enum EventType{
Я тут долго думал над обоими вариантами. В итоге вдохновился вот этим [обсуждением](https://stackoverflow.com/questions/6484003/enum-practices-define-inside-a-class-separately-make-public-private) и решил сделать внутренние енамы, т.к. в отрыве от ивента они не несут особого смысла, а так есть логическая связь.

2022-11-05 12:57 UTC, TomatoSoup0451 commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:h2:mem:testdb
Вернул на место как было

2022-11-05 13:10 UTC, TomatoSoup0451 commented on src/main/java/ru/yandex/practicum/filmorate/storage/feed/EventDbStorage.java
> +        String query = "SELECT event_id, user_id, event_id, user_id, timestamp, event_type," +
Поправил

2022-11-05 13:42 UTC, TomatoSoup0451 commented on src/main/java/ru/yandex/practicum/filmorate/storage/feed/EventDbStorage.java
> +    private void isUserExists(int id) {
Да, так пожалуй симпатичнее будет. Перенес проверку в EventService.

2022-11-05 13:46 UTC, TomatoSoup0451 commented on src/main/java/ru/yandex/practicum/filmorate/storage/feed/EventDbStorage.java
> +            throw new NotFoundException("id", String.format("user with id %d not found", id));
Все верно, эксепшена не будет. Я и не планировал его выкидавать на пустую ленту, даже тест такой написал) Копировал из другого класса и не убрал лишнее. Сейчас NotFoundException будет вылетать только если id пользователя вообще нет в таблице users

2022-11-05 16:06 UTC, AdalizEentropy approved these changes
Принято! =)

2022-11-06 09:28 UTC, AndreiNovikov1984 approved these changes

2022-11-06 09:28 UTC, AndreiNovikov1984 commented on src/main/java/ru/yandex/practicum/filmorate/service/EventService.java
> +    public List<Event> getFeedByUserId(int id) {
Как по мне, логичнее проверку проводить методом isUserExists. в методе userStorage.findById тоже вместо исключения логичнее использовать isUserExists.

2022-11-06 09:59 UTC, TomatoSoup0451 commented on src/main/java/ru/yandex/practicum/filmorate/service/EventService.java
> +    public List<Event> getFeedByUserId(int id) {
Он приватный - не получится использовать, поэтому используется единственный подходящий публичный

2022-11-06 10:38 UTC, merged