Add director
aleskerovv/java-filmorate pull request #11
Opened 2022-11-05 17:06 UTC by PavelDubovik

2022-11-05 21:31 UTC, AdalizEentropy requested changes
Всё отличненько написано, прям красота)) Добавила несколько вопросиков, которые наверное ты захочешь сделать ))

2022-11-05 21:31 UTC, AdalizEentropy commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        return null;
В моём пул-реквесте Денис предложил кинуть throw new UnsupportedOperationException("this type of operation not allowed");. Я с ним согласна))

2022-11-05 21:31 UTC, AdalizEentropy commented on src/main/resources/schema.sql
> +  NAME VARCHAR NOT NULL
Думаю лучше добавить ограничение длины для поля (аналогично названию фильма и т.д.)

2022-11-05 21:31 UTC, AdalizEentropy commented on src/main/resources/schema.sql
> +  FILM_ID INTEGER NOT NULL REFERENCES FILMS ON DELETE CASCADE,
А тут не надо в скобках добавлять колонку, на которую идет ссылка? Я просто немного другим объявлением пользовалась, и может быть именно при таком - не надо ))

2022-11-05 21:31 UTC, AdalizEentropy commented on src/main/java/ru/yandex/practicum/filmorate/storage/director/DirectorDbStorage.java
> +        String sqlQuery = "SELECT D.* FROM FILMS_DIRECTORS " +
А можешь плиз расставить в этом селекте алиасы? А то с трудом понимается, из какой именно таблицы ты достаешь ID и FILM_ID

2022-11-05 21:31 UTC, AdalizEentropy commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            StringBuilder sb = new StringBuilder("INSERT INTO FILMS_DIRECTORS (FILM_ID, DIRECTOR_ID) VALUES");
Какое изысканное решение))) А не хочешь попробовать jdbcTemplate.batchUpdate ? Нам с Ильясом ревьювер предлагал его использовать.

2022-11-05 21:31 UTC, AdalizEentropy commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        films.forEach(film -> film.setDirectors(new HashSet<>(directorService.getDirectorsByFilmId(film.getId()))));
Вариант рабочий, но при таком подходе кол-во запросов и подключений к БД будет рости линейно в зависимости от количества фильмов в списке (а их может быть огогошеньки много). 
Можно сделать вариант, как реализовал Ильяс для жанров или лайков выше: одним запросом вытаскивать все значения из таблицы продюсеров, а потом их маппить в фильм.

2022-11-05 21:31 UTC, AdalizEentropy commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                String sqlQueryLikes = "SELECT F.*, MR.NAME as MPA_NAME, COUNT(FL.USER_ID)\n" +
Наверное COUNT нам не надо в селекте возвращать

2022-11-06 11:36 UTC, TomatoSoup0451 requested changes
В целом все хорошо смотрится. Оставил пару комментариев

2022-11-06 11:36 UTC, TomatoSoup0451 commented on src/main/java/ru/yandex/practicum/filmorate/model/Director.java
> +    String name;
Думаю надо поля приватными сделать

2022-11-06 11:36 UTC, TomatoSoup0451 commented on src/main/java/ru/yandex/practicum/filmorate/storage/director/DirectorDbStorage.java
> +
По мне для одиночного id более подходящий метод - queryForObject. Сразу вернет один нужный объект без стрима. Аналогично тому, как это сделано в UserDbStorage, например.

2022-11-06 12:04 UTC, aleskerovv approved these changes, later dismissed

2022-11-06 12:04 UTC, aleskerovv commented on src/main/java/ru/yandex/practicum/filmorate/model/Director.java
> +public class Director {
private поля

2022-11-06 12:04 UTC, aleskerovv commented on src/main/java/ru/yandex/practicum/filmorate/storage/director/DirectorDbStorage.java
> +
Можно как Денис предложил, либо если хочется сделать отработку через orElseThrow(), можно попробовать через Optional(), но это на твое усмотрение

2022-11-06 12:04 UTC, aleskerovv commented on src/main/java/ru/yandex/practicum/filmorate/storage/director/DirectorDbStorage.java
> +        jdbcTemplate.update(connection -> {
(Opt) Я бы directors создал через SimpleJdbcInsert - кода будет меньше, а выполнять он будет те же самые действия. Пример можно посмотреть в UserDbStorage

2022-11-06 12:04 UTC, aleskerovv commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        films.forEach(film -> film.setDirectors(new HashSet<>(directorService.getDirectorsByFilmId(film.getId()))));
Соглашусь со Светой, такой подход будет быстрее работать и меньше грузить базу

2022-11-06 12:05 UTC, aleskerovv requested changes
Добавил пару комментариев, в целом всё ок

2022-11-06 14:33 UTC, PavelDubovik commented on src/main/java/ru/yandex/practicum/filmorate/storage/director/DirectorDbStorage.java
> +        String sqlQuery = "SELECT D.* FROM FILMS_DIRECTORS " +
Тут получается что у двух таблиц, нет полей с одинаковыми названиями, поэтому указал название полей без указания таблицы. Но ты возможно права, для лучшего чтения хорошо бы указывать алиасы. Добавил

2022-11-06 14:48 UTC, PavelDubovik commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            StringBuilder sb = new StringBuilder("INSERT INTO FILMS_DIRECTORS (FILM_ID, DIRECTOR_ID) VALUES");
Согласен. Видимо этот batchUpdate специально для таких случаем и сделан :)

2022-11-06 15:00 UTC, PavelDubovik commented on src/main/resources/schema.sql
> +  FILM_ID INTEGER NOT NULL REFERENCES FILMS ON DELETE CASCADE,
Такой вариант синтаксиса возможен. С твоего позволения не буду вность изменения.

2022-11-06 15:06 UTC, PavelDubovik commented on src/main/resources/schema.sql
> +  NAME VARCHAR NOT NULL
Режиссера с самым длинным именем, которого я нашел зовут Kiefer William Frederick Dempsey George Rufus Sutherland. Будем тогда от него и отталкиваться. Поставлю ограничение на 60

2022-11-06 16:02 UTC, TomatoSoup0451 requested changes

2022-11-06 16:02 UTC, TomatoSoup0451 commented on src/main/java/ru/yandex/practicum/filmorate/storage/director/DirectorDbStorage.java
> +
Я думаю Ильяс что-то вроде такого имел ввиду:

Optional.ofNullable(jdbcTemplate.queryForObject(sqlQuery, DirectorMapper::mapToDirector, id))
                .orElseThrow(()->new NotFoundException("id", String.format("Director with id = %d does not exist", id)));

try-catch вместе с optional на мой взгляд не так изящно смотрится. Два разных подхода в одну кучу смешиваются

2022-11-06 18:51 UTC, TomatoSoup0451 approved these changes

2022-11-06 19:33 UTC, aleskerovv approved these changes

2022-11-06 20:52 UTC, AdalizEentropy approved these changes
Огонь!)

2022-11-06 20:55 UTC, merged