First download. Implemented logic
aleskerovv/java-filmorate pull request #18
Opened 2022-11-08 12:17 UTC by YakupovRR

First try

2022-11-08 13:41 UTC, TomatoSoup0451 requested changes
Замечательно, но в паре мест пожалуй стоит поправить

2022-11-08 13:41 UTC, TomatoSoup0451 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        List<Integer> usersWithSimilarInterests = getIdUsersWithSimilarInterests(idRecommendedUser);
Предлагаю перенести проверку ниже и проверять на пустоту список в переменной userWithSimilarInterests, чтобы два раза подряд один и тот же метод не вызвать.

2022-11-08 13:41 UTC, TomatoSoup0451 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +                idRecommendedUser, limitFilms);
Наверное стоит переименовать метод, например getIdsFilmsRecomendations, чтобы с глагола начиналолось. В совокупности с названием переменной тяжеловато читается

2022-11-08 13:41 UTC, TomatoSoup0451 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +
Этот и последующие методы наверное можно сделать приватными. Из контроллера только один метод getRecommendations() используется в соответствии с API, а эти нужны только для внутреннего функционирования UserService, можно спрятать

2022-11-08 13:41 UTC, TomatoSoup0451 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    }
Тут лучше подойдет стандартное UnsupportedOperationException - обозначаем что хранение в памяти не поддерживает функционал по выдаче рекомендаций

2022-11-08 20:40 UTC, aleskerovv requested changes
Хороший, читаемый код, оставил комментарий касаемо логирования, в остальном вроде всё ок

2022-11-08 20:40 UTC, aleskerovv commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            log.info("Added to list film id " + i);
Считаю, что log.info лучше преобразовать в log.debug и отслеживать добавление только в дебажном логе или при переводе logger.properties в состояние level=DEBUG, иначе, основной лог будет слишком засорен
Нам в level=INFO достаточно знать, что в этот метод что-то поступило и отработало в том случае, если никаких ошибок не вызвано

2022-11-09 15:25 UTC, TomatoSoup0451 approved these changes
Отлично. Все рекомендации учтены

2022-11-09 16:40 UTC, aleskerovv approved these changes

2022-11-09 23:20 UTC, AdalizEentropy approved these changes
Очень круто написано! Замечаний нет)

2022-11-10 13:36 UTC, merged