working
aleskerovv/java-filmorate pull request #19
Opened 2022-11-08 19:41 UTC by AndreiNovikov1984

2022-11-08 21:21 UTC, aleskerovv requested changes
Код хорошо читается, в целом всё понятно
Оставил комментарий в слое с бизнес-логикой

2022-11-08 21:21 UTC, aleskerovv commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        }
Я бы попробовал найти более оптимальное решение в этой логике

2022-11-08 21:21 UTC, aleskerovv commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +                                  @RequestParam(value = "genreId", defaultValue = "-1", required = false) Integer genreId,
Интересное решение)

2022-11-09 05:39 UTC, AndreiNovikov1984 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        }
честно говоря эту часть я взял твою без изменений)))))) а что именно не нравится?

2022-11-09 05:44 UTC, aleskerovv commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        }
Меня немного озадачило больше ветвление
Логика полностью корректная, только реализация объемная получилась, ввиду добавления новых аргументов

2022-11-09 07:26 UTC, aleskerovv commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            query = "SELECT f.*, mr.name as mpa_name \n " +
Андрей, прости, я указатель не на те строки поставил
Мой комментарий, касаемо алгоритма, был к строкам 225-254

2022-11-09 15:30 UTC, TomatoSoup0451 approved these changes
Все выглядит хорошо

2022-11-09 16:40 UTC, aleskerovv approved these changes

2022-11-09 23:07 UTC, AdalizEentropy approved these changes
Всё хорошо написано! Ветвление с селектами выглядит громоздко, но в целом и такой вариант хороший. Если что, о красоте подумаем позже)))

2022-11-09 23:23 UTC, merged