Add new functions
aleskerovv/java-filmorate pull request #20
Opened 2022-11-10 14:02 UTC by aleskerovv

feat: added new Directors, Reviews, Events services. added recommendations service. films search by directors, genres, release year. added new functions for search common films between two users

2022-11-11 13:53 UTC, NikolaiDem requested changes

2022-11-11 13:53 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/AbstractDictionary.java
>      T getById(int id);
Кодстайл : добавить пустую строку между методами.

2022-11-11 13:53 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/director/DirectorStorage.java
> +    List<Director> getAll();
Кодстайл : добавить пустую строку между методами.
Поправить и остальные интерфейсы.

2022-11-11 13:53 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/event/EventDbStorage.java
> +public class EventDbStorage {
Лучше добавить и интерфейс к хранилищу, чтобы классы, его использующие, не подвергались модификации при изменении реализации хранилища.

2022-11-11 13:53 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/event/EventDbStorage.java
> +                " operation, entity_id FROM events WHERE user_id = ?";
Лучше добавить сортировку, чтобы лента событий была в упорядоченном виде.

2022-11-11 13:53 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/event/EventDbStorage.java
> +        Optional<Integer> id = Optional.of(keyHolder.getKey().intValue());
Здесь keyHolder.getKey().intValue() оборачивается в Optional, а потом безусловно из него извлекается. Таким образом его использование выглядит избыточным.
А если использовать Optional, то лучше сделать все действия через один "стрим", например,
        Optional.ofNullable(keyHolder.getKey())
            .ifPresentOrElse(key -> event.setEventId(key.intValue()), generate exception);
Аналогично для остальных хранилищ.

2022-11-11 13:53 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    private final DirectorService directorService;
Слой хранилищ работает с моделью данных и не занимается логикой программы. Он, можно сказать, является более низкоуровневым и устойчивым компонентом системы чем сервис. Поэтому смешивать хранилище с сервисом на уровне хранилища не рекомендуется. Лучше использовать зависимость только сервиса от хранилища.

2022-11-11 13:53 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        if ((genreId == -1) && (year == -1)) {
А если добавится еще один параметр для поиска, то количество веток может увеличиться вдвое. Можно сократить количество кода по аналогии с
        String whereYear = year != null ? " AND EXTRACT(YEAR FROM f.RELEASE_DATE) = " + year : "";
        String joinGenres = genreId != null ?  " left join FILMS_GENRES FG on f.ID = FG.FILM_ID " : "";
        String whereGenre = genreId != null ? " AND FG.GENRE_ID = " + genreId : "";

        String query = "SELECT f.*, mr.name as mpa_name \n " +
            "FROM FILMS f \n " +
            "left join MPA_RATING MR on f.MPA_RATE_ID = MR.MPA_RATE_ID \n " +
            joinGenres +
            " WHERE 1=1" +
            whereYear +
            whereGenre +
            " ORDER BY f.rate DESC, f.ID" +
            " LIMIT ?";

2022-11-11 13:53 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                    "UNION " +
union здесь избыточен, можно сделать одним запросом с джойнами.

2022-11-11 13:53 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                        "ORDER BY COUNT(FL.USER_ID) DESC, F.ID";
В таблице films есть поле rate, по нему можно сортировать вместо джойна к лайкам.

2022-11-11 13:53 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage.java
> +    List<Film> getAll();
Кодстайл : добавить пустые строки.

2022-11-11 13:53 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (filter.isBlank()) {
Для фронта если фильтр не задан, то лучше вернуть все фильмы. Так как ничего плохого не произошло)

2022-11-11 13:53 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                && (by.get(0).equals("title") || by.get(0).equals("director")))
title и director используются в коде несколько раз, можно их вынести в enum.
Тогда такая большая проверка будет избыточна.

2022-11-11 13:53 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            List<Integer> idFilmsRecommendedByUser = filmStorage.getRecommendations(i,
Лучше избавиться от множественных запросов к БД и за один селект получить ids фильмов от любителей кино с похожими интересами.

2022-11-11 13:53 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +                if (!filmsRecomendations.contains(idFilm)) {
Избавиться от таких проверок можно с помощью HashSet вместо ArrayList, например.

2022-11-11 13:53 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/model/Event.java
> +@Data
@Data и @Builder могут иметь конфликты при генерации одинаковых конструкторов. Если нужен билдер, то лучше вместо @Data использовать отдельные геттеры и сеттеры.

2022-11-11 13:53 UTC, NikolaiDem commented on src/main/resources/schema.sql
> +    TIMESTAMP         TIMESTAMP                         not null,
В названиях столбцов лучше не указывать зарезервированные слова.

2022-11-11 13:53 UTC, NikolaiDem commented on src/main/resources/schema.sql
> +    IS_POSITIVE  CHARACTER(10),
Почему не булево значение?

2022-11-11 13:53 UTC, NikolaiDem commented on src/test/java/ru/yandex/practicum/filmorate/storages/FilmDbStorageTest.java
>  class FilmDbStorageTest {
Добавить тесты для getFilmsByDirector(...) и getRecommendations(...)

2022-11-11 13:53 UTC, NikolaiDem commented on src/test/java/ru/yandex/practicum/filmorate/storages/UserDbStorageTest.java
> +
Добавить тест для getIdUsersWithSimilarInterests(...)

2022-11-13 05:26 UTC, PavelDubovik commented on src/test/java/ru/yandex/practicum/filmorate/storages/FilmDbStorageTest.java
>  class FilmDbStorageTest {
Для getFilmsByDirector() тесты добавил.

2022-11-13 20:26 UTC, NikolaiDem approved these changes

2022-11-13 20:26 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/model/enums/SearchParam.java
> +        return Stream.of(SearchParam.values())
Можно вынести в константы.

2022-11-13 20:26 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            films.add(filmStorage.findById(i));
Лучше в filmStorage добавить метод для получения фильмов по списку id
 filmStorage.findByIds(List<Integer> ids). 
Тогда можно избавиться от цикла и множественных запросов.

2022-11-15 21:05 UTC, merged