refactor: Учтены замечания ревьювера
aleskerovv/java-filmorate pull request #25
Opened 2022-11-12 20:15 UTC by AdalizEentropy

2022-11-12 22:57 UTC, aleskerovv approved these changes
Всё хорошо, все рекомендации ревьюера учтены.
Через enum действительно код выглядит приятнее

2022-11-13 06:34 UTC, PavelDubovik requested changes, later dismissed
По функционально части все отлично! По кодстайлу, я воспринял от ревьюера информацию немного по другому, поэтому оставил несколько комментариев.

2022-11-13 06:34 UTC, PavelDubovik commented on src/main/java/ru/yandex/practicum/filmorate/storage/director/DirectorStorage.java
>      List<Director> getAll();
Я добавил в своем коммите пустую строку тут же, но между методами. Я именно так понял замечаение ревьюера. :)

2022-11-13 06:34 UTC, PavelDubovik commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage.java
>      List<Film> getAll();
Возможно здесь стоит поправить и добавить пустые строки между методами.

2022-11-13 06:34 UTC, PavelDubovik commented on src/main/java/ru/yandex/practicum/filmorate/storage/AbstractDictionary.java
>      T getById(int id);
Хорошо бы добавить пустую строку между методами.

2022-11-13 07:10 UTC, TomatoSoup0451 approved these changes
Отлично

2022-11-13 08:25 UTC, AdalizEentropy commented on src/main/java/ru/yandex/practicum/filmorate/storage/director/DirectorStorage.java
>      List<Director> getAll();
Оке, тогда этот интерфейс не трогаю, а остальные - поправлю

2022-11-13 08:52 UTC, AndreiNovikov1984 approved these changes

2022-11-13 10:58 UTC, merged