Add recommendations
aleskerovv/java-filmorate pull request #26
Opened 2022-11-12 20:28 UTC by YakupovRR

2022-11-12 21:24 UTC, AdalizEentropy requested changes
Все замечания были учтены, супер! Вариант с массивом в целом рабочий, поэтому его можно оставить, а вот преобразование списка из массива выглядит странным.. попробуй плиз заменить.

2022-11-12 21:24 UTC, AdalizEentropy commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        String query;
Андрей удалял этот кусок кода. Надо будет после мержа проверить, что его изменения остались.

2022-11-12 21:24 UTC, AdalizEentropy commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    public List<Integer> getRecommendations(Integer[] usersWithSimilarInterests, Integer idRecommendedUser,
В целом и такой вариант верный. Правда я бы сделала еще проще, аналогично тому, как сейчас сделано для жанров и лайков.
![image](https://user-images.githubusercontent.com/104779716/201494958-8a34ab31-5f77-4ea8-9054-840208570ea4.png)
Плюс в таком подходе можно сразу фильмы доставать, а не только ID.

2022-11-12 21:24 UTC, AdalizEentropy commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        Integer[] users = usersWithSimilarInterests.toArray(new Integer[0]);
Попробуй написать так:
Integer[] users = usersWithSimilarInterests.toArray(new Integer[]{});

А то что-то меня пугает этот нолик внутри...

2022-11-12 23:02 UTC, aleskerovv approved these changes, later dismissed
Необходимо обновиться от актуальной ветки develop и запушить новый коммит, с учетом того, что @AndreiNovikov1984 ранее уже смерджил.

2022-11-12 23:02 UTC, aleskerovv commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        String query;
Я предлагаю вообще обновиться от ветки develop и по новой запушить коммит. Что бы избежать негативных последствий в дальнейшем.

2022-11-12 23:03 UTC, aleskerovv requested changes
Необходимо обновиться от актуальной ветки develop и запушить новый коммит, с учетом того, что @AndreiNovikov1984 ранее уже смерджил.

2022-11-13 12:05 UTC, AdalizEentropy approved these changes
ВсЁ отлично)

2022-11-13 12:19 UTC, aleskerovv approved these changes

2022-11-13 12:23 UTC, TomatoSoup0451 approved these changes
Отлично

2022-11-13 12:27 UTC, merged