feat: DAOs for filmorate DB, genre and mpa controllers, unit-test and mockMvc tests for new functions
aleskerovv/java-filmorate pull request #7
Opened 2022-10-15 20:45 UTC by aleskerovv

2022-10-15 20:47 UTC, aleskerovv commented
Николай, привет!
Подскажи, стоит ли удалить inMemory хранилища? 
Мы уже начали работу с БД, нужны ли нам в дальнейшем подобные классы?

2022-10-17 09:32 UTC, NikolaiDem requested changes

2022-10-17 09:32 UTC, NikolaiDem commented on src/main/resources/schema.sql
> +create table USERS
Для создания таблиц без их предварительного удаления можно использовать конструкцию вида:
 create table if not exists USERS

2022-10-17 09:32 UTC, NikolaiDem commented on src/main/resources/schema.sql
> +merge into GENRES(GENRE_ID, name)
Инициализация данных уже есть в data.sql

2022-10-17 09:32 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/GenreService.java
> +public class GenreService {
Добавить логирование в методы.

2022-10-17 09:32 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/MpaService.java
> +public class MpaService {
Добавить логирование в методы.

2022-10-17 09:32 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/model/Genre.java
> +@Component
Аннотация Component служит для обозначения класса бином, то есть управляемым контекстом спринга для инициализации, внедрения его в качестве зависимости и т.д. А классам модели данных такая функциональность не нужна, они просто POJO. 
Аннотацию Component удалить и для остальных классов в пакете model.

2022-10-17 09:32 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        userStorage.deleteFriend(id, friendId);
В addFriend(...) проверки существования пользователей есть, а здесь нет. Лучше привести к единообразию.

2022-10-17 09:32 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (user == null) throw new NotFoundException("id", String.format("user with id %d not found", id));
Проверка на существование есть же в Storage

2022-10-17 09:32 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            String genresQuery = "select fg.GENRE_ID, g2.NAME from FILMS_GENRES fg \n " +
Для уменьшения количества запросов к БД можно сразу получить сджойненную таблицу жанров с таблицей FILMS_GENRES и для каждой строки из полученного сета взять нужный фильм из films и добавить в него распарсенный жанр.
Для построчной обработки можно использовать метод JdbcTemplate 
  public void query(String sql, RowCallbackHandler rch, @Nullable Object... args) throws DataAccessException {
    this.query(sql, this.newArgPreparedStatementSetter(args), rch);
  }
Такой же способ можно применить к UserDbStorage.getAll()
Аналогично для findById(...) 
И лайки тоже нужно получить.

2022-10-17 09:32 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    public void addLike(Integer filmId, Integer userId) {
При добавлении или удалении лайка нужно обновлять rate у фильма.

2022-10-17 09:32 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        } catch (DataAccessException e) {
При добавлении лайка есть обработка исключений, при удалении нет. Можно удалить здесь, так как созданы хэндлеры исключений.

2022-10-17 09:32 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                    "LEFT JOIN FILMS_LIKES fl ON f.ID = fl.FILM_ID\n " +
От джойна к лайкам можно избавиться, потому что films.rate уже включает в себя это.

2022-10-17 09:32 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +public class UserDbStorage implements UserStorage {
В каких-то методах DataAccessException обрабатывается в каких-то нет. Лучше привести к единообразию. Если исключение перехватывается только лишь для логирования ошибки, то от этого можно избавиться в сервисе, потому что данную функцию выполняет ErrorHandler.

2022-10-18 18:46 UTC, closed without merging